---
- hosts: "master"
  tasks:
   - name: Install metallb Charts
     kubernetes.core.helm:
       name: metallb
       namespace: metallb-system
       create_namespace: true
       chart_ref: metallb/metallb
